version: '3.8'

services:
  inspecta:
    build:
      context: .
      dockerfile: Dockerfile
    image: inspecta:latest
    container_name: inspecta
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
      - "${MCP_SERVER_PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - BROWSER_HEADLESS=true
      - BROWSER_EXECUTABLE_PATH=/usr/bin/google-chrome
      - MAX_BROWSER_INSTANCES=${MAX_BROWSER_INSTANCES:-5}
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      - MAX_PAGE_CACHE_SIZE=${MAX_PAGE_CACHE_SIZE:-20}
      - RESPONSE_CACHE_ENABLED=${RESPONSE_CACHE_ENABLED:-true}
      - MCP_SERVER_ENABLED=${MCP_SERVER_ENABLED:-true}
      - MCP_SERVER_PORT=3001
    volumes:
      - ./data:/usr/src/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    shm_size: 1gb  # Shared memory for Chrome

  # Optional Redis service for distributed deployments
  # redis:
  #   image: redis:alpine
  #   container_name: inspecta-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   command: redis-server --appendonly yes

# Uncomment to use persistent Redis data
# volumes:
#   redis-data: 